name: Deploy Worker

on:
  push:
    branches:
      - main

  workflow_dispatch:


permissions:
  contents: read


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"


      # 安装依赖前清理，避免 node_modules 被上传
      - name: Install Dependencies
        run: |
          npm install


      # 删除不需要上传的文件
      - name: Prepare Assets
        run: |
          rm -rf node_modules
          rm -rf .git
          rm -rf .github
          rm -rf solara-assets.zip
          rm -rf Preview.gif


      - name: Check Files
        run: |
          echo "Deployment files:"
          ls -la


      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "4.112.0"
          command: deploy --config=wrangler.jsonc
